import './lib/setup';
import { LogLevel, SapphireClient, container } from '@sapphire/framework';
import { GoogleSpreadsheet } from "google-spreadsheet"
//TODO: extend me later
const client = new SapphireClient({
	defaultPrefix: '.',
	caseInsensitiveCommands: true,
	logger: {
		level: LogLevel.Debug
	},
	shards: 'auto',
	intents: [
		'GUILDS',
		'GUILD_MEMBERS',
		'GUILD_BANS',
		'GUILD_EMOJIS_AND_STICKERS',
		'GUILD_VOICE_STATES',
		'GUILD_MESSAGES',
		'GUILD_MESSAGE_REACTIONS',
		'DIRECT_MESSAGES',
		'DIRECT_MESSAGE_REACTIONS'
	]
});
container.sheets = new GoogleSpreadsheet('1jkAstqD-HpdqW61FL3HRVqaOtnYVh63jvZLlEJD2Lr0')



const main = async () => {
	try {
		client.logger.info('Logging in');
		await client.login();
		client.logger.info('logged in');

		await container.sheets.useServiceAccountAuth({
		// env var values are copied from service account credentials generated by google
		// see "Authentication" section in docs for more info
		client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL!,
		private_key: process.env.GOOGLE_PRIVATE_KEY!,
});
	} catch (error) {
		client.logger.fatal(error);
		client.destroy();
		process.exit(1);
	}
};

main();
